name: Generate Animations

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Create dist directory
        run: mkdir -p dist

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: samet-ari
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

      - name: Generate Matrix SVG
        run: python3 generate_matrix.py

      - name: Push all to output branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist
          keep_files: false
